---
collections:
# With just the collection name
# - my_namespace.my_collection

# The Galaxy URL to pull the collection from (default: ``--api-server`` from cmdline)
# With the collection name, version, and source options
- vyos.vyos